/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javanns_KernelInterface */

#ifndef _Included_javanns_KernelInterface
#define _Included_javanns_KernelInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfUnits
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfSpecialUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfSpecialUnits
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFirstUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getFirstUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNextUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNextUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setCurrentUnit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setCurrentUnit
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getCurrentUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getCurrentUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getUnitName
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitName
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    searchUnitName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_searchUnitName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    searchNextUnitName
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_searchNextUnitName
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitOutFuncName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getUnitOutFuncName
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitActFuncName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getUnitActFuncName
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitOutFunc
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitOutFunc
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitActFunc
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitActFunc
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitFTypeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getUnitFTypeName
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitActivation
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_getUnitActivation
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitActivation
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitActivation
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitInitialActivation
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_getUnitInitialActivation
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitInitialActivation
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitInitialActivation
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitOutput
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_getUnitOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitOutput
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitOutput
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitBias
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_getUnitBias
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitBias
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitBias
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitSubnetNo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getUnitSubnetNo
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitSubnetNo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitSubnetNo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitLayerNo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getUnitLayerNo
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitLayerNo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitLayerNo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_getUnitPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitNoAtPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getUnitNoAtPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitNoNearPosition
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getUnitNoNearPosition
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitTType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getUnitTType
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitTType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitTType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    freezeUnit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_freezeUnit
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    unfreezeUnit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_unfreezeUnit
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    isUnitFrozen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_isUnitFrozen
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitInputType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getUnitInputType
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitValueA
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_getUnitValueA
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitValueA
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitValueA
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    createDefaultUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_createDefaultUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    createUnit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DD)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_createUnit
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    createFTypeUnit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_createFTypeUnit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitFType
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitFType
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    copyUnit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_copyUnit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteUnitList
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteUnitList
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    createSiteTableEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_createSiteTableEntry
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    changeSiteTableEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_changeSiteTableEntry
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteSiteTableEntry
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteSiteTableEntry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFirstSiteTableEntry
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_getFirstSiteTableEntry
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNextSiteTableEntry
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_getNextSiteTableEntry
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getSiteTableFuncName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getSiteTableFuncName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFirstSite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setFirstSite
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setNextSite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setNextSite
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setSite
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setSite
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getSiteValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_getSiteValue
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getSiteFuncName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getSiteFuncName
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getSiteName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getSiteName
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setSiteName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setSiteName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    addSite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_addSite
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteSite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_deleteSite
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFirstPredUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getFirstPredUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNextPredUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNextPredUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getCurrentPredUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getCurrentPredUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFirstSuccUnit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getFirstSuccUnit
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNextSuccUnit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNextSuccUnit
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    isConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_isConnected
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    areConnected
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_areConnected
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    areConnectedWeight
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_areConnectedWeight
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getLinkWeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_getLinkWeight
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setLinkWeight
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setLinkWeight
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    createLink
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_createLink
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteLink
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteLink
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteAllInputLinks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteAllInputLinks
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteAllOutputLinks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteAllOutputLinks
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    jogWeights
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_jogWeights
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    jogCorrWeights
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_jogCorrWeights
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFirstFTypeEntry
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setFirstFTypeEntry
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setNextFTypeEntry
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setNextFTypeEntry
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFTypeEntry
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setFTypeEntry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFTypeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getFTypeName
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFTypeName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setFTypeName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFTypeActFuncName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getFTypeActFuncName
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFTypeActFunc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setFTypeActFunc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFTypeOutFuncName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getFTypeOutFuncName
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFTypeOutFunc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setFTypeOutFunc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFirstFTypeSite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setFirstFTypeSite
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setNextFTypeSite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_setNextFTypeSite
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFTypeSiteName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getFTypeSiteName
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFTypeSiteName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setFTypeSiteName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    createFTypeEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_createFTypeEntry
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteFTypeEntry
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteFTypeEntry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfFunctions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfFunctions
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFuncInfo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_getFuncInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    isFunction
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_isFunction
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFuncParamInfo
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_getFuncParamInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setInitFunc
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setInitFunc
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    getInitFunc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getInitFunc
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    initNet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_initNet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    updateSingleUnit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_updateSingleUnit
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUpdateFunc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getUpdateFunc
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUpdateFunc
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUpdateFunc
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    updateNet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_updateNet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setLearnFunc
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setLearnFunc
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    setFFLearnFunc
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setFFLearnFunc
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    setPruningFunc
 * Signature: (Ljava/lang/String;Ljava/lang/String;DDZIIDDZZ)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setPruningFunc
  (JNIEnv *, jobject, jstring, jstring, jdouble, jdouble, jboolean, jint, jint, jdouble, jdouble, jboolean, jboolean);

/*
 * Class:     javanns_KernelInterface
 * Method:    getLearnFunc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getLearnFunc
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getFFLearnFunc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getFFLearnFunc
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getPrunFunc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getPrunFunc
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    trainNet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_trainNet__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    trainFFNet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_trainFFNet__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    trainNet
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_trainNet__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    trainFFNet
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_trainFFNet__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     KernelInterface
 * Method:    trainNetFixedTime
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_KernelInterface_trainNetFixedTime__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     KernelInterface
 * Method:    trainNetFixedTime
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_KernelInterface_trainNetFixedTime__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setPatternNo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setPatternNo
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getPatternNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getPatternNo
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    deletePattern
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deletePattern
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    modifyPattern
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_modifyPattern
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setRemapFunc
 * Signature: (Ljava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setRemapFunc
  (JNIEnv *, jobject, jstring, jdoubleArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    showPattern
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_showPattern
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    newPattern
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_newPattern
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteAllPatterns
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteAllPatterns
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setShuffle
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setShuffle
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     javanns_KernelInterface
 * Method:    setSubShuffle
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setSubShuffle
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfPatterns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfPatterns
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getTotalNoOfSubPatterns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getTotalNoOfSubPatterns
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    allocNewPatternSet
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_allocNewPatternSet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    setPattern
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setPattern
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    delPattern
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_delPattern
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    getPatInfo
 * Signature: ()Ljavanns/KernelInterface$KernelPatternInfo;
 */
JNIEXPORT jobject JNICALL Java_javanns_KernelInterface_getPatInfo
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    defShowSubPat
 * Signature: ([I[I[I[I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_defShowSubPat
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    defTrainSubPat
 * Signature: ([I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_defTrainSubPat
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    alignSubPat
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_alignSubPat
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    getShapeOfSubPattern
 * Signature: (I)Ljavanns/KernelInterface$KernelSubPatShape;
 */
JNIEXPORT jobject JNICALL Java_javanns_KernelInterface_getShapeOfSubPattern
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    setClassDistribution
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setClassDistribution
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     javanns_KernelInterface
 * Method:    setClassInfo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setClassInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    useClassDistribution
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_useClassDistribution
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     javanns_KernelInterface
 * Method:    loadNet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_loadNet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    saveNet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_saveNet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    loadPattern
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_loadPattern
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    savePattern
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_savePattern
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    saveResult
 * Signature: (Ljava/lang/String;IIZZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_saveResult
  (JNIEnv *, jobject, jstring, jint, jint, jboolean, jboolean, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    symbolSearch
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_javanns_KernelInterface_symbolSearch
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getUnitDefaults
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_getUnitDefaults
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    setUnitDefaults
 * Signature: (DDIIILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setUnitDefaults
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jint, jstring, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    setSeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setSeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfInputUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfInputUnits
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfOutputUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfOutputUnits
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfSpecialInputUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfSpecialInputUnits
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfSpecialOutputUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfSpecialOutputUnits
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    resetNet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_resetNet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    allocateUnits
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_allocateUnits
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    deleteNet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_deleteNet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getClassNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getClassNo
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getN
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getM
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNa
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNa
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getMa
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getMa
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNb
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getMb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getMb
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    analyzer_error
 * Signature: (IIIZ)D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_analyzer_1error
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     javanns_KernelInterface
 * Method:    setSubPattern
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setSubPattern
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    setParallelMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setParallelMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     javanns_KernelInterface
 * Method:    setCascadeParams
 * Signature: (DLjava/lang/String;ZZLjava/lang/String;DIIILjava/lang/String;DIILjava/lang/String;[DZ)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_setCascadeParams
  (JNIEnv *, jobject, jdouble, jstring, jboolean, jboolean, jstring, jdouble, jint, jint, jint, jstring, jdouble, jint, jint, jstring, jdoubleArray, jboolean);

/*
 * Class:     javanns_KernelInterface
 * Method:    testNet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_testNet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    pruneNet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_pruneNet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    pruneNet_FirstStep
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_pruneNet_1FirstStep
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    pruneNet_Step
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_javanns_KernelInterface_pruneNet_1Step
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    pruneNet_LastStep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_pruneNet_1LastStep
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    pruneTrainNet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_pruneTrainNet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    pruneNetNow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_pruneNetNow
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    delCandUnits
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_delCandUnits
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getCurrPatternSetNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getCurrPatternSetNo
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getNoOfPatternSets
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javanns_KernelInterface_getNoOfPatternSets
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    getPatternSet
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getPatternSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     javanns_KernelInterface
 * Method:    getCurrPatternSet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javanns_KernelInterface_getCurrPatternSet
  (JNIEnv *, jobject);

/*
 * Class:     javanns_KernelInterface
 * Method:    renamePatternSet
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_renamePatternSet__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    renamePatternSet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_renamePatternSet__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    renameCurrPatternSet
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_renameCurrPatternSet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javanns_KernelInterface
 * Method:    resetSNNS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javanns_KernelInterface_resetSNNS
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
